      - id: prime-cache-3ccc412   # ← this is the step ID
        name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-3ccc412
          restore-keys: |
            cache-3ccc412

      - name: Show cache result
        run: echo "Cache hit/miss: ${{ steps.prime-cache-3ccc412.outputs.cache-hit }}"

