name: CI Cache Demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # ✅ Correctly set the step ID for caching
      - id: prime-cache-3ccc412   # ← this is the step ID
        name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-3ccc412
          restore-keys: |
            cache-3ccc412

      - name: Show cache result
        run: echo "Cache hit/miss: ${{ steps.prime-cache-3ccc412.outputs.cache-hit }}"

